#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_category:
  path: /admin/category
  controller: App\Controller\CategoryController::index
  defaults:
    title: "Categorie de voyages"

app_voyage:
  path: /admin/product
  controller: App\Controller\VoyageController::index
  defaults:
    title: "Les voyages"